# Classification Exercise

We'll be working with some California Census Data, we'll be trying to use various features of an individual to predict what class of income they belogn in (>50k or <=50k). 

Here is some information about the data:

<table>
<thead>
<tr>
<th>Column Name</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>age</td>
<td>Continuous</td>
<td>The age of the individual</td>
</tr>
<tr>
<td>workclass</td>
<td>Categorical</td>
<td>The type of employer the  individual has (government,  military, private, etc.).</td>
</tr>
<tr>
<td>fnlwgt</td>
<td>Continuous</td>
<td>The number of people the census  takers believe that observation  represents (sample weight). This  variable will not be used.</td>
</tr>
<tr>
<td>education</td>
<td>Categorical</td>
<td>The highest level of education  achieved for that individual.</td>
</tr>
<tr>
<td>education_num</td>
<td>Continuous</td>
<td>The highest level of education in  numerical form.</td>
</tr>
<tr>
<td>marital_status</td>
<td>Categorical</td>
<td>Marital status of the individual.</td>
</tr>
<tr>
<td>occupation</td>
<td>Categorical</td>
<td>The occupation of the individual.</td>
</tr>
<tr>
<td>relationship</td>
<td>Categorical</td>
<td>Wife, Own-child, Husband,  Not-in-family, Other-relative,  Unmarried.</td>
</tr>
<tr>
<td>race</td>
<td>Categorical</td>
<td>White, Asian-Pac-Islander,  Amer-Indian-Eskimo, Other, Black.</td>
</tr>
<tr>
<td>gender</td>
<td>Categorical</td>
<td>Female, Male.</td>
</tr>
<tr>
<td>capital_gain</td>
<td>Continuous</td>
<td>Capital gains recorded.</td>
</tr>
<tr>
<td>capital_loss</td>
<td>Continuous</td>
<td>Capital Losses recorded.</td>
</tr>
<tr>
<td>hours_per_week</td>
<td>Continuous</td>
<td>Hours worked per week.</td>
</tr>
<tr>
<td>native_country</td>
<td>Categorical</td>
<td>Country of origin of the  individual.</td>
</tr>
<tr>
<td>income</td>
<td>Categorical</td>
<td>"&gt;50K" or "&lt;=50K", meaning  whether the person makes more  than \$50,000 annually.</td>
</tr>
</tbody>
</table>

## Follow the Directions in Bold. If you get stuck, check out the solutions lecture.

### THE DATA

** Read in the census_data.csv data with pandas**

In [12]:
import pandas as pd

In [13]:
data = pd.read_csv('census_data.csv')

In [14]:
data.head()

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

** TensorFlow won't be able to understand strings as labels, you'll need to use pandas .apply() method to apply a custom function that converts them to 0s and 1s. This might be hard if you aren't very familiar with pandas, so feel free to take a peek at the solutions for this part.**

** Convert the Label column to 0s and 1s instead of strings.**

In [15]:
def label_fix(label):
    if(label == ' <=50K'):
        return 0
    else:
        return 1

In [16]:
data['income_bracket'] = data['income_bracket'].apply(label_fix)

In [17]:
data.head()

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

### Perform a Train Test Split on the Data

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_data = data.drop('income_bracket',axis=1)
y_label = data['income_bracket']

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_label, test_size=0.3, random_state=101)

### Create the Feature Columns for tf.esitmator

** Take note of categorical vs continuous values! **

In [21]:
data.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

** Import Tensorflow **

In [22]:
import tensorflow as tf

** Create the tf.feature_columns for the categorical values. Use vocabulary lists or just use hash buckets. **

In [23]:
gender = tf.feature_column.categorical_column_with_vocabulary_list("gender", ["Female", "Male"])
occupation = tf.feature_column.categorical_column_with_hash_bucket("occupation", hash_bucket_size=1000)
marital_status = tf.feature_column.categorical_column_with_hash_bucket("marital_status", hash_bucket_size=1000)
relationship = tf.feature_column.categorical_column_with_hash_bucket("relationship", hash_bucket_size=1000)
education = tf.feature_column.categorical_column_with_hash_bucket("education", hash_bucket_size=1000)
workclass = tf.feature_column.categorical_column_with_hash_bucket("workclass", hash_bucket_size=1000)
native_country = tf.feature_column.categorical_column_with_hash_bucket("native_country", hash_bucket_size=1000)

** Create the continuous feature_columns for the continuous values using numeric_column **

In [24]:
age = tf.feature_column.numeric_column("age")
education_num = tf.feature_column.numeric_column("education_num")
capital_gain = tf.feature_column.numeric_column("capital_gain")
capital_loss = tf.feature_column.numeric_column("capital_loss")
hours_per_week = tf.feature_column.numeric_column("hours_per_week")

** Put all these variables into a single list with the variable name feat_cols **

In [25]:
feat_cols = [gender,occupation,marital_status,relationship,education,workclass,native_country,
            age,education_num,capital_gain,capital_loss,hours_per_week]

### Create Input Function

** Batch_size is up to you. But do make sure to shuffle!**

In [26]:
input_func = tf.estimator.inputs.pandas_input_fn( x = x_train, y = y_train, batch_size=100, num_epochs=None, shuffle=True)

#### Create your model with tf.estimator

**Create a LinearClassifier.(If you want to use a DNNClassifier, keep in mind you'll need to create embedded columns out of the cateogrical feature that use strings, check out the previous lecture on this for more info.)**

In [27]:
model = tf.estimator.LinearClassifier(feature_columns=feat_cols)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/f1/nnt7c4mn2rv2jhd9lpbk0g4w0000gp/T/tmpwj__zbbn
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/f1/nnt7c4mn2rv2jhd9lpbk0g4w0000gp/T/tmpwj__zbbn', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x181b94ad30>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

** Train your model on the data, for at least 5000 steps. **

In [28]:
model.train(input_fn=input_func, steps=5000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/f1/nnt7c4mn2rv2jhd9lpbk0g4w0000gp/T/tmpwj__zbbn/model.ckpt.
INFO:tensorflow:loss = 69.3147, step = 1
INFO:tensorflow:global_step/sec: 109.59
INFO:tensorflow:loss = 190.287, step = 101 (0.914 sec)
INFO:tensorflow:global_step/sec: 161.278
INFO:tensorflow:loss = 2117.79, step = 201 (0.624 sec)
INFO:tensorflow:global_step/sec: 214.671
INFO:tensorflow:loss = 2633.88, step = 301 (0.464 sec)
INFO:tensorflow:global_step/sec: 221.483
INFO:tensorflow:loss = 228.612, step = 401 (0.452 sec)
INFO:tensorflow:global_step/sec: 231.187
INFO:tensorflow:loss = 73.7716, step = 501 (0.433 sec)
INFO:tensorflow:global_step/sec: 245.496
INFO:tensorflow:loss = 52.7549, step = 601 (0.407 sec)
INFO:tensorflow:global_step/sec: 252.221
INFO:tensorflow:loss = 50.517, step = 701 (0.398 sec)
INFO:tensorflow:global_step/sec: 219.962
INFO:tensorflow:loss = 164.236, step = 801 (0.452 sec)
INFO:tensorflow:global_step/sec: 243.697
INFO:tensorflow:loss = 138.862, step = 901 (0.413 sec)
INFO:tensorflow:global_step/sec: 208.688
INFO:tensorflow:loss = 99.8076, step = 1001 (0.476 sec)
INFO:tensorflow:global_step/sec: 225.077
INFO:tensorflow:loss = 38.7411, step = 1101 (0.447 sec)
INFO:tensorflow:global_step/sec: 179.128
INFO:tensorflow:loss = 54.9232, step = 1201 (0.554 sec)
INFO:tensorflow:global_step/sec: 190.836
INFO:tensorflow:loss = 43.7493, step = 1301 (0.526 sec)
INFO:tensorflow:global_step/sec: 213.376
INFO:tensorflow:loss = 119.3, step = 1401 (0.472 sec)
INFO:tensorflow:global_step/sec: 215.937
INFO:tensorflow:loss = 55.2186, step = 1501 (0.462 sec)
INFO:tensorflow:global_step/sec: 199.806
INFO:tensorflow:loss = 35.6868, step = 1601 (0.499 sec)
INFO:tensorflow:global_step/sec: 227.447
INFO:tensorflow:loss = 85.3866, step = 1701 (0.439 sec)
INFO:tensorflow:global_step/sec: 230.148
INFO:tensorflow:loss = 33.1332, step = 1801 (0.435 sec)
INFO:tensorflow:global_step/sec: 172.474
INFO:tensorflow:loss = 69.1275, step = 1901 (0.580 sec)
INFO:tensorflow:global_step/sec: 185.233
INFO:tensorflow:loss = 100.307, step = 2001 (0.542 sec)
INFO:tensorflow:global_step/sec: 246.423
INFO:tensorflow:loss = 34.9639, step = 2101 (0.404 sec)
INFO:tensorflow:global_step/sec: 223.713
INFO:tensorflow:loss = 45.7359, step = 2201 (0.447 sec)
INFO:tensorflow:global_step/sec: 227.638
INFO:tensorflow:loss = 53.634, step = 2301 (0.439 sec)
INFO:tensorflow:global_step/sec: 150.222
INFO:tensorflow:loss = 43.1898, step = 2401 (0.668 sec)
INFO:tensorflow:global_step/sec: 156.474
INFO:tensorflow:loss = 115.531, step = 2501 (0.639 sec)
INFO:tensorflow:global_step/sec: 191.553
INFO:tensorflow:loss = 36.1432, step = 2601 (0.520 sec)
INFO:tensorflow:global_step/sec: 232.231
INFO:tensorflow:loss = 42.2205, step = 2701 (0.430 sec)
INFO:tensorflow:global_step/sec: 242.341
INFO:tensorflow:loss = 37.5009, step = 2801 (0.413 sec)
INFO:tensorflow:global_step/sec: 245.242
INFO:tensorflow:loss = 264.747, step = 2901 (0.410 sec)
INFO:tensorflow:global_step/sec: 202.31
INFO:tensorflow:loss = 58.8599, step = 3001 (0.492 sec)
INFO:tensorflow:global_step/sec: 182.284
INFO:tensorflow:loss = 70.1649, step = 3101 (0.548 sec)
INFO:tensorflow:global_step/sec: 181.583
INFO:tensorflow:loss = 41.1348, step = 3201 (0.549 sec)
INFO:tensorflow:global_step/sec: 179.998
INFO:tensorflow:loss = 33.7252, step = 3301 (0.555 sec)
INFO:tensorflow:global_step/sec: 178.114
INFO:tensorflow:loss = 157.191, step = 3401 (0.563 sec)
INFO:tensorflow:global_step/sec: 220.675
INFO:tensorflow:loss = 47.4362, step = 3501 (0.456 sec)
INFO:tensorflow:global_step/sec: 184.063
INFO:tensorflow:loss = 54.7583, step = 3601 (0.541 sec)
INFO:tensorflow:global_step/sec: 178.56
INFO:tensorflow:loss = 39.9112, step = 3701 (0.558 sec)
INFO:tensorflow:global_step/sec: 184.085
INFO:tensorflow:loss = 36.6378, step = 3801 (0.543 sec)
INFO:tensorflow:global_step/sec: 183.128
INFO:tensorflow:loss = 61.0155, step = 3901 (0.546 sec)
INFO:tensorflow:global_step/sec: 158.686
INFO:tensorflow:loss = 37.8384, step = 4001 (0.630 sec)
INFO:tensorflow:global_step/sec: 201.925
INFO:tensorflow:loss = 53.9207, step = 4101 (0.500 sec)
INFO:tensorflow:global_step/sec: 222.791
INFO:tensorflow:loss = 62.9462, step = 4201 (0.447 sec)
INFO:tensorflow:global_step/sec: 246.159
INFO:tensorflow:loss = 94.579, step = 4301 (0.406 sec)
INFO:tensorflow:global_step/sec: 242.66
INFO:tensorflow:loss = 35.7396, step = 4401 (0.412 sec)
INFO:tensorflow:global_step/sec: 230.85
INFO:tensorflow:loss = 512.654, step = 4501 (0.435 sec)
INFO:tensorflow:global_step/sec: 240.489
INFO:tensorflow:loss = 151.121, step = 4601 (0.414 sec)
INFO:tensorflow:global_step/sec: 247.127
INFO:tensorflow:loss = 262.382, step = 4701 (0.408 sec)
INFO:tensorflow:global_step/sec: 247.511
INFO:tensorflow:loss = 52.6172, step = 4801 (0.400 sec)
INFO:tensorflow:global_step/sec: 248.416
INFO:tensorflow:loss = 36.8014, step = 4901 (0.403 sec)
INFO:tensorflow:Saving checkpoints for 5000 into /var/folders/f1/nnt7c4mn2rv2jhd9lpbk0g4w0000gp/T/tmpwj__zbbn/model.ckpt.
INFO:tensorflow:Loss for final step: 84.4814.

### Evaluation

** Create a prediction input function. Remember to only supprt X_test data and keep shuffle=False. **

In [31]:
pred_fn = tf.estimator.inputs.pandas_input_fn(x=x_test, batch_size=len(x_test), shuffle = False)

** Use model.predict() and pass in your input function. This will produce a generator of predictions, which you can then transform into a list, with list() **

In [33]:
pred_gen = model.predict(input_fn = pred_fn)

** Each item in your list will look like this: **

In [34]:
predictions = list(pred_gen)

INFO:tensorflow:Restoring parameters from /var/folders/f1/nnt7c4mn2rv2jhd9lpbk0g4w0000gp/T/tmpwj__zbbn/model.ckpt-5000

** Create a list of only the class_ids key values from the prediction list of dictionaries, these are the predictions you will use to compare against the real y_test values. **

In [40]:
final_pred=[pred['class_ids'][0] for pred in predictions]

In [41]:
final_pred

[0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 ...]

** Import classification_report from sklearn.metrics and then see if you can figure out how to use it to easily get a full report of your model's performance on the test data. **

In [44]:
from sklearn.metrics import classification_report

In [45]:
print(classification_report(y_test,final_pred))

             precision    recall  f1-score   support

          0       0.90      0.90      0.90      7436
          1       0.67      0.68      0.67      2333

avg / total       0.84      0.84      0.84      9769

# Great Job!